import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import ReactQueryProvider from "@/lib/provider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { Geist, Geist_Mono, Radley } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const radley = Radley({
    variable: "--font-radley",
    subsets: ["latin"],
    weight: "400",
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${radley.variable} antialiased`}>
                <GoogleOAuthProvider clientId="113118193592-loc110rrqru2gmg3ahr94771n1c7hp8j.apps.googleusercontent.com">
                    <ReactQueryProvider>
                        {children}
                        <Toaster />
                    </ReactQueryProvider>
                </GoogleOAuthProvider>
            </body>
        </html>
    );
}
